DROP DATABASE IF EXISTS pwds;
CREATE DATABASE pwds;
USE pwds;

DROP TABLE IF EXISTS pwds;
CREATE TABLE pwds(
	id BINARY(16) NOT NULL,
	salt   VARBINARY(256) NOT NULL,
	pwd    VARBINARY(256) NOT NULL,
	n      MEDIUMINT UNSIGNED NOT NULL,
	r      MEDIUMINT UNSIGNED NOT NULL,
	p      MEDIUMINT UNSIGNED NOT NULL,
	keyLen MEDIUMINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);

DROP USER IF EXISTS 't_c_pwds'@'%';
CREATE USER 't_c_pwds'@'%' IDENTIFIED BY 'T@sk-Pwd5';
GRANT SELECT ON pwds.* TO 't_c_pwds'@'%';
GRANT INSERT ON pwds.* TO 't_c_pwds'@'%';
GRANT UPDATE ON pwds.* TO 't_c_pwds'@'%';
GRANT DELETE ON pwds.* TO 't_c_pwds'@'%';
GRANT EXECUTE ON pwds.* TO 't_c_pwds'@'%';