version: '3.7'
services:

  redis:
    container_name: "redis-5.0"
    image: redis:5.0-rc4-alpine
    ports:
    - "6379:6379"

  db:
    container_name: "mariadb-10.3"
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
    - "3306:3306"